name: Node.js CI & Linter

on: [push, pull_request]

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create pull request
        id: open-pr
        uses: repo-sync/pull-request@v3
        with:
          destination_branch: "master"
          pr_title: "PLACEHOLDER TITLE"
          pr_draft: true
          pr_reviewer: "olivermclane"
  build:
    name: Linting Code Base
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_HTML: true
          FILTER_REGEX_EXCLUDE: .*node_modules/.*
          GITHUB_TOKEN: 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
