name: Node.js CI & Linter

on: [push, pull_request]

on:
  push:
    branches:
      - feature-1

permissions:
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        run: |
          gh_pr_up() { gh pr create $* || gh pr edit $* }
          gh_pr_up --title "Pull Request Title" --body "Description"

  build:
    name: Linting Code Base
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_HTML: true
          GITHUB_TOKEN: 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
